name: deferrables_demo
description: Demonstration of deferrables for long-running external jobs

tasks:
  # Task 1: Simulate a BigQuery job
  bigquery_job:
    executor: python
    file: tasks.py
    function: simulate_bigquery_job

  # Task 2: Simulate a custom HTTP job
  custom_http_job:
    executor: python
    file: tasks.py
    function: simulate_custom_http_job

  # Task 3: Multiple deferred jobs in parallel
  multiple_jobs:
    executor: python
    file: tasks.py
    function: multiple_jobs

  # Task 4: Process results after deferred job completes
  process_results:
    executor: python
    file: tasks.py
    function: process_results
    depends_on:
      - bigquery_job
