name: deferrables_demo
description: Demonstration of deferrables for long-running external jobs

types:
  DeferredOutput:
    deferred: [str]
  ProcessResultsOutput:
    message: str
    upstream_tasks: [str]

tasks:
  bigquery_job:
    executor: python
    file: tasks.py
    function: simulate_bigquery_job
    input_type: {}
    output_type: types.DeferredOutput
    inputs: {}

  custom_http_job:
    executor: python
    file: tasks.py
    function: simulate_custom_http_job
    input_type: {}
    output_type: types.DeferredOutput
    inputs: {}

  multiple_jobs:
    executor: python
    file: tasks.py
    function: multiple_jobs
    input_type: {}
    output_type: types.DeferredOutput
    inputs: {}

  process_results:
    executor: python
    file: tasks.py
    function: process_results
    depends_on: [bigquery_job]
    input_type:
      bigquery_job: types.DeferredOutput
    output_type: types.ProcessResultsOutput
    inputs:
      bigquery_job:
        ref: tasks.bigquery_job.output
