#!/bin/bash
# Dump the current database schema after all migrations have been applied
# This generates a canonical schema.sql file showing the final state

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE="$SCRIPT_DIR/../schema.sql"

echo "Dumping schema to $OUTPUT_FILE..."

# Use pg_dump to get clean DDL
docker compose exec -T postgres pg_dump -U postgres -d orchestrator \
    --schema-only \
    --no-owner \
    --no-privileges \
    --exclude-table=_sqlx_migrations \
    | grep -v "^--" \
    | grep -v "^$" \
    | grep -v "^SET " \
    | grep -v "^SELECT pg_catalog" \
    | grep -v "^\\\\restrict" \
    | grep -v "^\\\\unrestrict" \
    | sed '1i\
-- Canonical database schema (generated from migrations)\
-- DO NOT EDIT - this file is auto-generated by scripts/dump-schema.sh\
-- To modify the schema, create a new migration in migrations/\
' > "$OUTPUT_FILE"

echo "✓ Schema dumped to $OUTPUT_FILE"
echo ""
echo "This shows the current state after all migrations have been applied."
echo "To modify the schema, create a new migration file in migrations/"
