-- Canonical database schema (generated from migrations)
-- DO NOT EDIT - this file is auto-generated by scripts/dump-schema.sh
-- To modify the schema, create a new migration in migrations/

CREATE TABLE public.runs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    workflow_id uuid NOT NULL,
    status text NOT NULL,
    triggered_by text DEFAULT 'manual'::text NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT runs_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'running'::text, 'success'::text, 'failed'::text, 'cancelled'::text])))
);
CREATE TABLE public.tasks (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    run_id uuid NOT NULL,
    task_index integer NOT NULL,
    status text NOT NULL,
    execution_name text,
    params jsonb,
    output jsonb,
    error text,
    dispatched_at timestamp with time zone,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT tasks_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'dispatched'::text, 'running'::text, 'success'::text, 'failed'::text, 'cancelled'::text])))
);
CREATE TABLE public.workflows (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    description text,
    job_name text NOT NULL,
    region text DEFAULT 'us-central1'::text NOT NULL,
    project text NOT NULL,
    task_params jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    executor_type text DEFAULT 'cloudrun'::text NOT NULL,
    CONSTRAINT workflows_executor_type_check CHECK ((executor_type = ANY (ARRAY['cloudrun'::text, 'process'::text])))
);
ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_run_id_task_index_key UNIQUE (run_id, task_index);
ALTER TABLE ONLY public.workflows
    ADD CONSTRAINT workflows_name_key UNIQUE (name);
ALTER TABLE ONLY public.workflows
    ADD CONSTRAINT workflows_pkey PRIMARY KEY (id);
CREATE INDEX idx_runs_status ON public.runs USING btree (status);
CREATE INDEX idx_runs_workflow_id ON public.runs USING btree (workflow_id);
CREATE INDEX idx_tasks_execution_name ON public.tasks USING btree (execution_name) WHERE (execution_name IS NOT NULL);
CREATE INDEX idx_tasks_run_id ON public.tasks USING btree (run_id);
CREATE INDEX idx_tasks_run_status ON public.tasks USING btree (run_id, status);
CREATE INDEX idx_tasks_status ON public.tasks USING btree (status);
CREATE INDEX idx_tasks_status_run_id ON public.tasks USING btree (status, run_id) WHERE (status = ANY (ARRAY['pending'::text, 'dispatched'::text, 'running'::text]));
CREATE INDEX idx_workflows_executor_type ON public.workflows USING btree (executor_type);
ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES public.workflows(id);
ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;
