name: Data Pipeline

on: [workflow_dispatch]

jobs:
  extract:
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.extract_data.outputs.data }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Extract data
        id: extract_data
        run: |
          python scripts/extract.py > output.txt
          data=$(tail -1 output.txt)
          echo "data=$data" >> $GITHUB_OUTPUT

  transform:
    runs-on: ubuntu-latest
    needs: extract
    outputs:
      data: ${{ steps.transform_data.outputs.data }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Transform data
        id: transform_data
        run: |
          python scripts/transform.py '${{ needs.extract.outputs.data }}' > output.txt
          data=$(tail -1 output.txt)
          echo "data=$data" >> $GITHUB_OUTPUT

  load:
    runs-on: ubuntu-latest
    needs: transform
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Load data
        run: python scripts/load.py '${{ needs.transform.outputs.data }}'
